### PR TITLE
Fix for under -std=c99 version style (comile error fix)

### PR DESCRIPTION
**Pull request by AirVan21**
Hi! 
Just tried your project to create simple transitions between regex => nfa => dfa.
Found some problems with running Makefile, so want to provide some extra info for future users.

Two points:
1. To my mind 'bison' should be added in dependencies
2. Counter initialization in for-loop scope will cause problems without -std=c99

Hope it wil be useful!

### CODE REVIEW

**Comment by wader** [comment]
Thanks!
You mean to add some more notes about dependencies to the readme? which packages to install etc?

**Comment by wader** [comment]
Not sure i follow the changes to `faexample.c`. Can you explain more?

**Comment by AirVan21** [comment]
Sorry about changes in faexample.c (I will do it only for me in the branch), so I reverted that commit.

About dependencies - yep, to readme (I hadn't bison installed, that is why I had strange mistakes)

**Comment by wader** [comment]
What do you think of adding `-std=gnu99` to `CFLAGS` instead? seems to work fine with clang also. Also that seems to also fix a missing `typeof` warning with new gcc versions. Or do you need to compile using some old compiler?

**Comment by AirVan21** [comment]
I don't have any problems with `-std=gnu99` flag, so it seems that it's the best solution. 
(I though that you had some compiler restrictions). Should I revert previous commit or it's possible just to add flag to `CFLAGS`?

**Comment by wader** [comment]
No problem for me. Yes i just added it to `CFLAGS` on master now.
Thanks! let me know if you have any other issues. Nice to see other people using the lib :+1:

**Comment by wader** [comment]
Also added note about packages

**Pull request closed without merging**
